apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: aditikhemkaq2
  name: aditipod1
spec:
  containers:
  - image: nginx
    name: adiahocpod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}